// The file below was generated by Grok.
// Implements the NOTICE view on the left side bar.

const vscode = require("vscode");

let view = null;

// Enable the notice view and display given markdown text.
function showMarkdown(markdown) {
  if (!view) {
    vscode.window.registerWebviewViewProvider("apio.sidebar.notice", {
      resolveWebviewView(wv) {
        view = wv;
        view.webview.options = { enableScripts: false };
        render();
      }
    });
    vscode.commands.executeCommand("setContext", "apio.sidebar.notice.enabled", true);
  }

  const md = markdown.trim();

  function render() {
    if (!view) return;

    vscode.commands.executeCommand("markdown.api.render", md).then(html => {
      view.webview.html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  body, vscode-body, .markdown-body {
    margin: 0 !important;
    padding: 8px 16px !important;   /* tight but readable */
    font-family: var(--vscode-editor-font-family);
    font-size: var(--vscode-editor-font-size);
    color: var(--vscode-editor-foreground);
    background: var(--vscode-editor-background);
    line-height: 1.5;
  }
  /* THIS LINE IS THE NUCLEAR FIX */
  .markdown-body > :first-child { margin-top: 0 !important; padding-top: 0 !important; }
  h1,h2,h3,h4,h5,h6 { margin: 0.4em 0 0.2em !important; }
  a { color: var(--vscode-textLink-foreground); }
</style>
</head>
<body class="markdown-body">
  ${html}
</body>
</html>`;
    });
  }

  render();
}

module.exports = { showMarkdown };